# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/helm_release/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module HelmRelease
    include Pangea::Resources::ResourceBuilder

    define_resource :helm_release,
      attributes_class: Helm::Types::ReleaseAttributes,
      outputs: { id: :id },
      map: [:chart, :name],
      map_present: [:description, :keyring, :max_history, :namespace, :postrender, :repository, :repository_ca_file, :repository_cert_file, :repository_key_file, :repository_password, :repository_username, :set, :set_list, :set_sensitive, :timeout, :values],
      map_bool: [:atomic, :cleanup_on_fail, :create_namespace, :dependency_update, :devel, :disable_crd_hooks, :disable_openapi_validation, :disable_webhooks, :force_update, :lint, :pass_credentials, :recreate_pods, :render_subchart_notes, :replace, :reset_values, :reuse_values, :skip_crds, :upgrade_install, :verify, :wait, :wait_for_jobs]
  end
  module Helm
    include HelmRelease
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Helm)
