# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Helm::Types
  include Dry.Types()

  class ReleaseAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Helm::Types

    attribute :chart, T::String
    attribute :name, T::String
    attribute? :atomic, T::Bool.optional
    attribute? :cleanup_on_fail, T::Bool.optional
    attribute? :create_namespace, T::Bool.optional
    attribute? :dependency_update, T::Bool.optional
    attribute? :description, T::String.optional
    attribute? :devel, T::Bool.optional
    attribute? :disable_crd_hooks, T::Bool.optional
    attribute? :disable_openapi_validation, T::Bool.optional
    attribute? :disable_webhooks, T::Bool.optional
    attribute? :force_update, T::Bool.optional
    attribute? :keyring, T::String.optional
    attribute? :lint, T::Bool.optional
    attribute? :max_history, T::Float.optional
    attribute? :namespace, T::String.optional
    attribute? :pass_credentials, T::Bool.optional
    attribute? :postrender, T::Array.of(T::Hash).optional
    attribute? :recreate_pods, T::Bool.optional
    attribute? :render_subchart_notes, T::Bool.optional
    attribute? :replace, T::Bool.optional
    attribute? :repository, T::String.optional
    attribute? :repository_ca_file, T::String.optional
    attribute? :repository_cert_file, T::String.optional
    attribute? :repository_key_file, T::String.optional
    attribute? :repository_password, T::String.optional
    attribute? :repository_username, T::String.optional
    attribute? :reset_values, T::Bool.optional
    attribute? :reuse_values, T::Bool.optional
    attribute? :set, T::Array.of(T::Hash).optional
    attribute? :set_list, T::Array.of(T::Hash).optional
    attribute? :set_sensitive, T::Array.of(T::Hash).optional
    attribute? :skip_crds, T::Bool.optional
    attribute? :timeout, T::Float.optional
    attribute? :upgrade_install, T::Bool.optional
    attribute? :values, T::Array.of(T::String).optional
    attribute? :verify, T::Bool.optional
    attribute? :wait, T::Bool.optional
    attribute? :wait_for_jobs, T::Bool.optional
  end
end
