# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea-core'
require 'terraform-synthesizer'

# Helm resources
require_relative 'pangea/resources/helm_release/resource'

# Helm module aggregator
require_relative 'pangea/resources/helm'
