# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a helm_release resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::HelmRelease do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { chart: 'test-value', name: 'test-value' } }

  describe ':helm_release' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'helm_release', 'test')
        validate_required_attributes(config, [:chart, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.helm_release('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:helm_release)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.helm_release('test', required_attrs)

        expect(ref.id).to eq("${helm_release.test.id}")
        expect(ref.manifest).to eq("${helm_release.test.manifest}")
        expect(ref.metadata).to eq("${helm_release.test.metadata}")
        expect(ref.status).to eq("${helm_release.test.status}")
        expect(ref.version).to eq("${helm_release.test.version}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'helm_release', 'test')
        expect(config).not_to have_key('manifest')
        expect(config).not_to have_key('metadata')
        expect(config).not_to have_key('status')
        expect(config).not_to have_key('version')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ atomic: true, cleanup_on_fail: true, create_namespace: true, dependency_update: true, description: 'test-value', devel: true, disable_crd_hooks: true, disable_openapi_validation: true, disable_webhooks: true, force_update: true, keyring: 'test-value', lint: true, max_history: 3.14, namespace: 'test-value', pass_credentials: true, postrender: [{ 'key1' => 'val1' }], recreate_pods: true, render_subchart_notes: true, replace: true, repository: 'test-value', repository_ca_file: 'test-value', repository_cert_file: 'test-value', repository_key_file: 'test-value', repository_password: 'test-value', repository_username: 'test-value', reset_values: true, reuse_values: true, set: [{ 'key1' => 'val1' }], set_list: [{ 'key1' => 'val1' }], set_sensitive: [{ 'key1' => 'val1' }], skip_crds: true, timeout: 3.14, upgrade_install: true, values: ['test-value'], verify: true, wait: true, wait_for_jobs: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'helm_release', 'full')
        expect(config).to have_key('atomic')
        expect(config).to have_key('cleanup_on_fail')
        expect(config).to have_key('create_namespace')
        expect(config).to have_key('dependency_update')
        expect(config).to have_key('description')
        expect(config).to have_key('devel')
        expect(config).to have_key('disable_crd_hooks')
        expect(config).to have_key('disable_openapi_validation')
        expect(config).to have_key('disable_webhooks')
        expect(config).to have_key('force_update')
        expect(config).to have_key('keyring')
        expect(config).to have_key('lint')
        expect(config).to have_key('max_history')
        expect(config).to have_key('namespace')
        expect(config).to have_key('pass_credentials')
        expect(config).to have_key('postrender')
        expect(config).to have_key('recreate_pods')
        expect(config).to have_key('render_subchart_notes')
        expect(config).to have_key('replace')
        expect(config).to have_key('repository')
        expect(config).to have_key('repository_ca_file')
        expect(config).to have_key('repository_cert_file')
        expect(config).to have_key('repository_key_file')
        expect(config).to have_key('repository_password')
        expect(config).to have_key('repository_username')
        expect(config).to have_key('reset_values')
        expect(config).to have_key('reuse_values')
        expect(config).to have_key('set')
        expect(config).to have_key('set_list')
        expect(config).to have_key('set_sensitive')
        expect(config).to have_key('skip_crds')
        expect(config).to have_key('timeout')
        expect(config).to have_key('upgrade_install')
        expect(config).to have_key('values')
        expect(config).to have_key('verify')
        expect(config).to have_key('wait')
        expect(config).to have_key('wait_for_jobs')
      end
    end

    context 'optional attributes' do
      it 'includes atomic when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(atomic: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('atomic')
      end

      it 'omits atomic when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('atomic')
      end
      it 'includes cleanup_on_fail when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(cleanup_on_fail: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('cleanup_on_fail')
      end

      it 'omits cleanup_on_fail when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('cleanup_on_fail')
      end
      it 'includes create_namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(create_namespace: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('create_namespace')
      end

      it 'omits create_namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('create_namespace')
      end
      it 'includes dependency_update when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(dependency_update: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('dependency_update')
      end

      it 'omits dependency_update when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('dependency_update')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes devel when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(devel: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('devel')
      end

      it 'omits devel when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('devel')
      end
      it 'includes disable_crd_hooks when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(disable_crd_hooks: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('disable_crd_hooks')
      end

      it 'omits disable_crd_hooks when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('disable_crd_hooks')
      end
      it 'includes disable_openapi_validation when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(disable_openapi_validation: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('disable_openapi_validation')
      end

      it 'omits disable_openapi_validation when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('disable_openapi_validation')
      end
      it 'includes disable_webhooks when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(disable_webhooks: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('disable_webhooks')
      end

      it 'omits disable_webhooks when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('disable_webhooks')
      end
      it 'includes force_update when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(force_update: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('force_update')
      end

      it 'omits force_update when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('force_update')
      end
      it 'includes keyring when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(keyring: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('keyring')
      end

      it 'omits keyring when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('keyring')
      end
      it 'includes lint when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(lint: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('lint')
      end

      it 'omits lint when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('lint')
      end
      it 'includes max_history when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(max_history: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('max_history')
      end

      it 'omits max_history when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('max_history')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes pass_credentials when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(pass_credentials: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('pass_credentials')
      end

      it 'omits pass_credentials when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('pass_credentials')
      end
      it 'includes postrender when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(postrender: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('postrender')
      end

      it 'omits postrender when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('postrender')
      end
      it 'includes recreate_pods when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(recreate_pods: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('recreate_pods')
      end

      it 'omits recreate_pods when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('recreate_pods')
      end
      it 'includes render_subchart_notes when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(render_subchart_notes: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('render_subchart_notes')
      end

      it 'omits render_subchart_notes when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('render_subchart_notes')
      end
      it 'includes replace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(replace: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('replace')
      end

      it 'omits replace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('replace')
      end
      it 'includes repository when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(repository: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('repository')
      end

      it 'omits repository when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('repository')
      end
      it 'includes repository_ca_file when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(repository_ca_file: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('repository_ca_file')
      end

      it 'omits repository_ca_file when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('repository_ca_file')
      end
      it 'includes repository_cert_file when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(repository_cert_file: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('repository_cert_file')
      end

      it 'omits repository_cert_file when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('repository_cert_file')
      end
      it 'includes repository_key_file when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(repository_key_file: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('repository_key_file')
      end

      it 'omits repository_key_file when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('repository_key_file')
      end
      it 'includes repository_password when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(repository_password: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('repository_password')
      end

      it 'omits repository_password when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('repository_password')
      end
      it 'includes repository_username when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(repository_username: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('repository_username')
      end

      it 'omits repository_username when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('repository_username')
      end
      it 'includes reset_values when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(reset_values: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('reset_values')
      end

      it 'omits reset_values when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('reset_values')
      end
      it 'includes reuse_values when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(reuse_values: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('reuse_values')
      end

      it 'omits reuse_values when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('reuse_values')
      end
      it 'includes set when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(set: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('set')
      end

      it 'omits set when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('set')
      end
      it 'includes set_list when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(set_list: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('set_list')
      end

      it 'omits set_list when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('set_list')
      end
      it 'includes set_sensitive when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(set_sensitive: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('set_sensitive')
      end

      it 'omits set_sensitive when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('set_sensitive')
      end
      it 'includes skip_crds when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(skip_crds: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('skip_crds')
      end

      it 'omits skip_crds when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('skip_crds')
      end
      it 'includes timeout when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(timeout: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('timeout')
      end

      it 'omits timeout when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('timeout')
      end
      it 'includes upgrade_install when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(upgrade_install: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('upgrade_install')
      end

      it 'omits upgrade_install when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('upgrade_install')
      end
      it 'includes values when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(values: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('values')
      end

      it 'omits values when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('values')
      end
      it 'includes verify when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(verify: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('verify')
      end

      it 'omits verify when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('verify')
      end
      it 'includes wait when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(wait: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('wait')
      end

      it 'omits wait when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('wait')
      end
      it 'includes wait_for_jobs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('opt', required_attrs.merge(wait_for_jobs: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'opt')
        expect(config).to have_key('wait_for_jobs')
      end

      it 'omits wait_for_jobs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'helm_release', 'minimal')
        expect(config).not_to have_key('wait_for_jobs')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:repository_password]
        expect(sensitive_fields).to include(:repository_password)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts atomic=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(atomic: val)
          synth.helm_release("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'helm_release', "bool_#{val}")
          expect(config['atomic']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts cleanup_on_fail=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(cleanup_on_fail: val)
          synth.helm_release("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'helm_release', "bool_#{val}")
          expect(config['cleanup_on_fail']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts create_namespace=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(create_namespace: val)
          synth.helm_release("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'helm_release', "bool_#{val}")
          expect(config['create_namespace']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts dependency_update=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(dependency_update: val)
          synth.helm_release("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'helm_release', "bool_#{val}")
          expect(config['dependency_update']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts devel=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(devel: val)
          synth.helm_release("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'helm_release', "bool_#{val}")
          expect(config['devel']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts disable_crd_hooks=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disable_crd_hooks: val)
          synth.helm_release("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'helm_release', "bool_#{val}")
          expect(config['disable_crd_hooks']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts disable_openapi_validation=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disable_openapi_validation: val)
          synth.helm_release("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'helm_release', "bool_#{val}")
          expect(config['disable_openapi_validation']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts disable_webhooks=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disable_webhooks: val)
          synth.helm_release("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'helm_release', "bool_#{val}")
          expect(config['disable_webhooks']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts force_update=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(force_update: val)
          synth.helm_release("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'helm_release', "bool_#{val}")
          expect(config['force_update']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts lint=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(lint: val)
          synth.helm_release("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'helm_release', "bool_#{val}")
          expect(config['lint']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts pass_credentials=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(pass_credentials: val)
          synth.helm_release("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'helm_release', "bool_#{val}")
          expect(config['pass_credentials']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts recreate_pods=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(recreate_pods: val)
          synth.helm_release("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'helm_release', "bool_#{val}")
          expect(config['recreate_pods']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts render_subchart_notes=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(render_subchart_notes: val)
          synth.helm_release("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'helm_release', "bool_#{val}")
          expect(config['render_subchart_notes']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts replace=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(replace: val)
          synth.helm_release("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'helm_release', "bool_#{val}")
          expect(config['replace']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts reset_values=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(reset_values: val)
          synth.helm_release("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'helm_release', "bool_#{val}")
          expect(config['reset_values']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts reuse_values=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(reuse_values: val)
          synth.helm_release("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'helm_release', "bool_#{val}")
          expect(config['reuse_values']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts skip_crds=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(skip_crds: val)
          synth.helm_release("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'helm_release', "bool_#{val}")
          expect(config['skip_crds']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts upgrade_install=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(upgrade_install: val)
          synth.helm_release("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'helm_release', "bool_#{val}")
          expect(config['upgrade_install']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts verify=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(verify: val)
          synth.helm_release("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'helm_release', "bool_#{val}")
          expect(config['verify']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts wait=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(wait: val)
          synth.helm_release("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'helm_release', "bool_#{val}")
          expect(config['wait']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts wait_for_jobs=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(wait_for_jobs: val)
          synth.helm_release("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'helm_release', "bool_#{val}")
          expect(config['wait_for_jobs']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'helm_release', 'typed')
        expect(config['chart']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.helm_release('first', required_attrs)
        synth.helm_release('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'helm_release')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :helm_release,
    method: :helm_release,
    required_attrs: { chart: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :manifest, :metadata, :status, :version],
    sensitive_fields: [:repository_password],
    immutable_fields: [],
    boolean_fields: [:atomic, :cleanup_on_fail, :create_namespace, :dependency_update, :devel, :disable_crd_hooks, :disable_openapi_validation, :disable_webhooks, :force_update, :lint, :pass_credentials, :recreate_pods, :render_subchart_notes, :replace, :reset_values, :reuse_values, :skip_crds, :upgrade_install, :verify, :wait, :wait_for_jobs]
end
